version: 2.1

setup: << pipeline.parameters.run-setup >>

orbs:
  path-filtering: circleci/path-filtering@0.0.2

parameters:
  run-setup:
    type: boolean
    default: true
  run-frontend:
    type: boolean
    default: false
  run-backend:
    type: boolean
    default: false

jobs:
  frontend:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: "echo 'Hello from Frontend!'"
      - run: cat frontend/README.md

  backend:
    machine: true
    steps:
      - checkout
      - run: "echo 'Hello from Backend!'"
      - run: cat backend/README.md

  backend-build-job:
    docker:
      - image: alpine
    steps:
      - run: "echo 'Continuing module B'"
      - run: env

workflows:
  pre:
    when: << pipeline.parameters.run-setup >>
    jobs:
      - path-filtering/filter:
          # Compare files on main
          base-revision: main
          # Config for continuation; herein we reuse this config itself
          config-path: .circleci/config.yml
          # 3-column space-separated table for mapping; `path-to-test parameter-to-set value-for-parameter` for each row
          mapping: |
            .* run-setup false
            frontend/.* run-frontend true
            backend/.* run-backend true
  frontend:
    when: << pipeline.parameters.run-frontend >>
    jobs:
      - frontend
  backend:
    when: << pipeline.parameters.run-backend >>
    jobs:
      - backend
      - backend-build-job:
          requires:
            - backend
